### ISSUE TITLE
exp build:ios fails when multi factor auth is enabled for Apple account

### ISSUE THREAD

**Issue by krstffr** [expo/exp#17]
When running `exp build:ios` using my Apple account which uses multi factor auth I get an error after inputting my Apple ID/Password/Team ID. I get the "Here's your 6 digit code!" popup on my mac, but the CLI hangs before I get a chance to enter it with the following error:

`[exp] Server error when validating credentials.`

Is multi factor auth not supported?

**Comment by roberttod** [comment]
I had the exact same issue. Turning off 2FA resolved it for me.

**Comment by krstffr** [comment]
@roberttod yeah I figured that was one way around it, though I wouldn't say it solved the problem really (but thanks for the suggestion/workaround!). 

Using exponent shouldn't require me to degrade my apple account security.

**Comment by ccheever** [comment]
hi @krstffr -- we want to fix this but it will take some time. it's nontrivial to do automated login around 2FA.

completely agree that you should not have to degrade your account security -- this is just a limitation of exponent for the time being.

**Comment by krstffr** [comment]
@ccheever great, thanks! I totally understand that it's a nontrivial thing to implement. Looking forward to this feature in the future.

**Comment by roberttod** [comment]
Thanks @ccheever. It would be good to add to the docs and/or the error message that for now 2FA is not supported.

**Comment by ide** [comment]
@roberttod thanks for the suggestion, our docs now mention that 2FA isn't support yet (https://docs.getexponent.com/versions/v10.0.0/guides/building-standalone-apps.html#if-you-choose-to-build-for-ios)

**Comment by ChenLi0830** [comment]
I turned off the 2-step authentication. However, now every time I log in the website, security questions will be asked. I suspect that might be the reason why my exp build:ios failed.

**Comment by brentvatne** [comment]
this is being tracked on https://github.com/expo/expo/issues/160
