### ISSUE TITLE
Outdated lodash (and possibly gulp)

### ISSUE THREAD

**Issue by krstffr** [expo/exp#21]
When installing exp a warning is raised about using `lodash-node` instead of the `lodash` package. I thought I would fix this annoyance and submit a pull request, but running `npm run watch` I get the error `gulp.series is not a function`, and maybe it's something about the incorrect gulp version, but at that point I kind of gave up since it's probably easier for you guys with the proper gulp versions/setups to just update the lodash package :)

(Would be kind of great if it was easier to work on this repo though, so if you feel like it it would be great if you resolved the gulp thing as well!)

**Comment by dikaiosune** [comment]
Hey! Sorry for the delay and that you're having issues with our gulp setup. I'm working on a few things right now but will be circling back to make a bunch of `exp` improvements in the very near future. I'll leave this open as a reminder. If you still want to make contributions but are having issues with gulp, definitely drop by [our slack](https://slack.getexponent.com) and say hi!

**Comment by krstffr** [comment]
@dikaiosune sure, cool!

**Comment by martin-rueegg** [comment]
Hi,
I still get

```
npm WARN deprecated lodash-node@3.10.2: This package is discontinued. Use lodash@^4.0.0.
```

Can the [dependency](https://github.com/expo/exp/blob/a864f353b54ab0b94e4e2eff5e0a32e356d2e4da/package.json#L74) be updated or would it break the code?

Thanks,
Martin.

**Comment by brentvatne** [comment]
we updated this and it will be included in the next release so the warning will go away
