### ISSUE TITLE
ERROR: Unexpected end of data : blank-2.0.1.tar

### ISSUE THREAD

**Issue by Pourya8366** [expo/exp#32]
when i run `exp init` after i choose blank, this error been shown:
```
Process exited with non-zero code: 2
ERROR: Unexpected end of data : blank-2.0.1.tar

Process exited with non-zero code: 2
```
and the setup been terminated!
how can i fix that?

i have windows 10 build 14393.693 64 bit
node version: 6.9.4

**Comment by dikaiosune** [comment]
Hi! Sorry to hear you're having problems getting started. Are you able to download this file manually?

https://s3.amazonaws.com/exp-starter-apps/blank-2.0.1.tar.gz

If you are able to download this and extract it, you should be able to run `exp start` directly in the directory it creates. If that still fails and you're behind a proxy of some kind, make sure the HTTP_PROXY and HTTPS_PROXY environment variables are set.

If neither of these steps work, could you let me know what sort of errors you encountered in trying them?
