### ISSUE TITLE
Environment-based build/publishing

### ISSUE THREAD

**Issue by OFranke** [expo/exp#33]
Hi,

I wonder if it would be possible to create builds and publish over the air updates according to the different environments I have.
Lets say I have 3 Environments:
Local: My local environment, running local Backend Api's and the Exponent App
Test: A remote test environment, where testusers will test new builds, connected to my test environment API
Production: the production environment, connected to my production backend API

What I would like to do now is to build my app with different configurations that access my Local, Test and Production backend APIs. The command "exp build:ios test" should create an .ipa file which loads my test environment configuration, whereas "exp build:ios production" should create an .ipa file which loads my production configuration.
Also when I want to publish a new version via over the air update, the first thing I want to do is to just publish it to the apps that have the test environment loaded before going into production mode.

I hope this makes sense, as I am not quite experienced in mobile developing. Anyway if that does not make sense, could you point me to the right direction in how to manage different environments with Exponent?

Best regards,
Oliver

**Comment by jesseruder** [comment]
This all makes sense. We're planning on adding something like this within the next few months.

For now I'd suggest writing a short script that changes the `slug` field in exp.json before publishing. You could change slug to `YourApp-staging` or `YourApp-dev` right before calling `exp publish`

**Comment by brentvatne** [comment]
Tracking this in https://github.com/expo/expo/issues/134

**Comment by oliverbenns** [comment]
I wrote a bash script to handle this: https://github.com/oliverbenns/expo-deploy
