### ISSUE TITLE
Exp Publish Hangs on Codeship

### ISSUE THREAD

**Issue by alexprice91** [expo/exp#39]
deployment script:
```
exp login -u $EXP_USERNAME -p $EXP_PASSWORD
exp publish --non-interactive
```
![screen shot 2017-03-18 at 12 43 33 am](https://cloud.githubusercontent.com/assets/4140149/24115395/34a1d696-0d71-11e7-9b37-ae199907bb7c.png)

Sometimes the script goes through, but the majority of the time it hangs. Also, it looks like the same script is working on travis builds.

**Comment by brentvatne** [comment]
cc @jesseruder @dikaiosune

**Comment by dikaiosune** [comment]
@alexprice91 is this app open source, and if so can you link to the codeship configuration you're using for it?

Also, is watchman installed as part of your build configuration?

**Comment by alexprice91** [comment]
The app is not open sourced. My configuration is pretty straight forward (I used the codeship UI to set it up.

set up:
```
nvm install node
nvm use node
npm install -g exp
exp --version
```

deployment:
```
exp login -u $EXP_USERNAME -p $EXP_PASSWORD
exp publish --non-interactive
```

**Comment by alexprice91** [comment]
I'm not sure if watchman is installed or not...

**Comment by alexprice91** [comment]
If it is a requirement for the build, I would imagine it is installed, since the build periodically passes

**Comment by brentvatne** [comment]
@alexprice91 - it's not a requirement but it makes things a lot faster

**Comment by leimd** [comment]
hi @alexprice91,

I'm running into the same problem, I am wondering was this ever resolved? what was the solution?

Thanks,

Tom
