### ISSUE TITLE
I don't think exp is actually checking for existing builds

### ISSUE THREAD

**Issue by JulianKingman** [expo/exp#43]
I just ran two builds, pretty much one right after the other, and it didn't detect the prior build. Is something misconfigured, or does it mean something else when it says `[exp] No currently active or previous builds for this project.`? I assume it's checking version numbers and things.

**Comment by skevy** [comment]
Hi there. Thanks for reporting this. We've been able to repro this issue in certain circumstances, and we have planned improvements to the standalone app builder infrastructure in the near future.

To be clear, this is a bug, and not something you've misconfigured.

**Comment by brentvatne** [comment]
moving discussion to https://github.com/expo/expo/issues/171

**Comment by kishorejethava** [comment]
Getting same message!!
`[exp] No currently active or previous builds for this project.`
Any Solution?
