### ISSUE TITLE
APK build with permissions

### ISSUE THREAD

**Issue by antonybudianto** [expo/exp#44]
Hello, 

I just tried to use `exp build:android` to get an APK and submit it to the store, but I got these warnings:
```
Your app has an apk with version code 1 that requests the following permission(s): android.permission.CAMERA,android.permission.READ_PHONE_STATE,android.permission.READ_CONTACTS. Apps using these permissions in an APK are required to have a privacy policy set.
```

My app doesn't even use camera, access contact, or read phone state.
Can I somehow control the permissions?

Thanks!

**Comment by ccheever** [comment]
Hi-

You'll have to detach/eject if you want to customize these things.

Here is some more info:
https://forums.expo.io/t/can-i-customize-which-permissions-are-asked-when-a-user-installs-my-standalone-app-from-the-play-store/160

Charlie

**Comment by simison** [comment]
For anyone who ends up here, seems like this might be available soon:

https://expo.canny.io/feature-requests/p/customize-android-permissions

**Comment by Albinzr** [comment]
I'm also having same issue and if we are ejecting from expo... all the work you did with expo to make build faster is going to wast

**Comment by simison** [comment]
I believe this is now in since SDK v19 and it's documented here:

https://docs.expo.io/versions/latest/guides/configuration.html#permissions
