### ISSUE TITLE
[exp] Android: There was an error with this build. Please try again.

### ISSUE THREAD

**Issue by Josecc** [expo/exp#45]
This is my first app with expo and it runs with the expo app. However, when I try to build it for android with exp build:adroid and check status I get the following message:

```
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] Android: There was an error with this build. Please try again.
```

The output from exp build:android was the following:
```
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Starting build process...
[exp] Publishing...
[exp] Published
[exp] Your URL is

https://exp.host/@josecc/abcs

[exp] Building...
[exp] Build successfully started, it may take a few minutes to complete. Run "exp build:status" to monitor it.
```
Any idea what could be causing this error?

**Comment by Josecc** [comment]
Here's the diagnostic command url: https://exp-xde-diagnostics.s3.amazonaws.com/josecc-e7a2e65d-ebfc-4185-9437-9f2b7ecbd444.tar.gz.

**Comment by dikaiosune** [comment]
Hi! Sorry for the delay here (note that our [Slack](https://slack.expo.io) and [Forums](https://forums.expo.io) tend to be more active).

It looks like there may be an issue with the apostrophe in your app's name, can you try removing that and see if it works? It looks like there is a bug on our end with escaping these properly. We're working on a fix for this at the moment, but I think if you remove the apostrophe you should be able to work around the bug until we have the fix deployed.

**Comment by Josecc** [comment]
@dikaiosune That solved it!! Thank you very much Adam!

**Comment by btk** [comment]
As I experienced `&` is also no go for app name. Thank you @dikaiosune

**Comment by dikaiosune** [comment]
Hey everyone! I deployed a fix for the unescaped ampersands, quotes, apostrophes, etc. Let us know if you run into any issues!
