### ISSUE TITLE
remove DS_Store dotfiles from `exp init`

### ISSUE THREAD

**Issue by clindsey** [expo/exp#46]
It's weird to me that `DS_Store` files are included on a linux/ubuntu system, because those only come from mac's finder app.

I've attached a screenshot showing how I created a fresh project with `exp init` (version 39.0.0) and it has DS_Store files.

<img width="1201" alt="screen shot 2017-04-11 at 14 36 39" src="https://cloud.githubusercontent.com/assets/11408/24932205/48c8eec4-1ec5-11e7-8d62-336f278b03b9.png">

**Comment by jesseruder** [comment]
Fixed!
