### ISSUE TITLE
Add option to remove/unpublish project

### ISSUE THREAD

**Issue by JulianKingman** [expo/exp#47]
I feel bad taking up server space with demo apps that I don't need, It would be handy if I could list and remove them if they were no longer needed.

**Comment by ide** [comment]
The server space for an average bundle costs us less than half a penny a year, it's not an issue. If you would like to make a project not visible from your profile screen in the Expo client, republish it with `"privacy": "unlisted"` in your exp.json file (docs: https://docs.expo.io/versions/v15.0.0/guides/configuration.html#privacy).
