### ISSUE TITLE
[feature request] exp version *

### ISSUE THREAD

**Issue by JulianKingman** [expo/exp#48]
It would be handy to have a version incrementer like there is for npm, i.e. `npm version [patch/minor/major]`. Obviously not mission-critical, but I find my npm and exp versions getting out of sync. Ideally I could update both at the same time.

**Comment by ide** [comment]
I believe Expo will fall back to the version listed in package.json if the field is missing from exp.json, which sounds like it would do what you want.

**Comment by JulianKingman** [comment]
Nice, that's perfect :)
