### ISSUE TITLE
[feature request] Ability to specify another JSON file when running/building

### ISSUE THREAD

**Issue by ccuilla** [expo/exp#49]
Currently exp assumes `exp.json` as the config file. Would be nice to set this on teh command line with something like `--settings myconfig.json` to be able to have different confid for dev, stage, production or whatever reason.

**Comment by ide** [comment]
Thanks for the suggestion. We don't have a settings flag for this right now but one thing you could try is to make several subdirectories in your project called dev, staging, etc... and in each create a barebones package.json (leave out the dependencies -- only run npm/Yarn in the main parent dir) and exp.json. Then open one of those new subdirectories with exp/XDE and it should apply the subdir's exp.json and package.json.

**Comment by brentvatne** [comment]
moving this to https://github.com/expo/expo/issues/134

**Comment by oliverbenns** [comment]
I wrote a bash script to handle this: https://github.com/oliverbenns/expo-deploy
