### ISSUE TITLE
Cannot create project with exp init

### ISSUE THREAD

**Issue by softnodelabs** [expo/exp#50]
Hi,

I upgraded my exp version but now when I use "exp init" it asks for project type first and then it exits with the error message:
"(node:8500) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Path must be a string. Received undefined (node:8500) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

I'm using Windows 10 1703.

**Comment by jesseruder** [comment]
Hi! Sorry about that. This should be fixed in version 40.0.2.

**Comment by softnodelabs** [comment]
Thanks. I Updated to the latest version and it works as it should.
