### ISSUE TITLE
Expo.Google.logInAsync error 12501 for release

### ISSUE THREAD

**Issue by 7ynk3r** [expo/exp#51]
I'm getting an error trying to authenticate with Google using my Android standalone app. 

The error message is the following:
```
Status(statusCode=unknown status code: 12501, resolution=null)
```
I'm using 
```
    "expo": "^15.0.2",
    "react": "~15.4.0",
    "react-native": "https://github.com/exponent/react-native/archive/sdk-15.0.0.tar.gz"
```

All other configurations work, except Android standalone.

I followed the steps for https://docs.expo.io/versions/v15.0.0/sdk/google.html this in my current app and in a fresh new one as well, obtaning the same result.

Some people is fixing the problem by creating a Web Client Id, which doesn't make any sense to me http://stackoverflow.com/questions/33583326/new-google-sign-in-android/37657942#37657942

Any advice? Things to try? 

Thanks,
JM

**Comment by janicduplessis** [comment]
Are you passing `androidClientId` to `logInAsync`? It needs to be a web client id (I know it's weird).

**Comment by 7ynk3r** [comment]
Hi @janicduplessis,

Yes, I'm passing `androidClientId`, and `androidStandaloneAppClientId` as well for release. The only scenario that doesn't work is `androidStandaloneAppClientId`.

If I use a web client id for `androidStandaloneAppClientId`, do I have to provide `Authorized JavaScript origins` and `Authorized JavaScript origins`?

I'm still debugging the issue. I'm trying to get OAuth to work in a standard Android App, signing it for release. I'm having some issues but I expect it to work and use the `google-services.json` to verify what I suppose Expo is generating (looking at the code that reads `exp.json`).

Is there a way to see the `google-services.json` Expo is generating? 

Thanks you so much!
JM

**Comment by 7ynk3r** [comment]
Found the solution, after so much time spent. 

`behavior` only works with `web`, and not with the default value `system`. 

It's easy to reproduce, just follow the steps to configure a standalone android app. You'll see that only works for `behavior` equals `web`.

The documentation should be changed to reflect this fact.

Cheers,
JM

**Comment by brentvatne** [comment]
Moved to https://github.com/expo/expo/issues/69 to consolidate issues
