### ISSUE TITLE
[feature request] exp url, option to get public URL

### ISSUE THREAD

**Issue by JulianKingman** [expo/exp#52]
Currently, `exp url` get's the local url, it would be great if there was an option to get the public one (e.g. `exp url --public`). I did a presentation using expo recently, and if I had had this feature, I could have published it and gave everyone in attendance a permanently accessible link. Same goes for group testing.

**Comment by dikaiosune** [comment]
I agree this would be nice to have. In the meantime, you should see the URL you get when you run `exp publish`.

**Comment by JulianKingman** [comment]
Yep, but no QR code.

**Comment by brentvatne** [comment]
feel free to send a PR for this! closing this issue as we're moving issues over to expo/expo
