### ISSUE TITLE
Error when detaching a project

### ISSUE THREAD

**Issue by fbarrailla** [expo/exp#53]
I'm getting an error when I try to detach an expo project with `exp` v40.0.2

```
Configuring iOS dependencies...
Cleaning up iOS...
[exp] ENOTEMPTY: directory not empty, rmdir '.../temp-ios-directory/ios/Pods/Headers'
```

I'm using MacOS Sierra (10.12)

**Comment by terribleben** [comment]
Does this prevent your project from working? It should be harmless. If it's blocking you, maybe just try discarding local changes and detaching again.

**Comment by fbarrailla** [comment]
Thank you for your answer. Yes it prevents the detaching to be done, what changes should I discard ?

**Comment by terribleben** [comment]
We looked into this a bit more, and we think the issue may happen if there is another process doing work inside the same folder while detach is happening. For example, if you have Dropbox sync enabled in this folder, I recommend temporarily turning it off.

By "discard local changes" I meant if you are using version control, just go back to whatever state you were in before you ran `exp detach`.

**Comment by fbarrailla** [comment]
I tried again and it worked fine 💯. I wasn't able to reproduce the problem, I tried with the project folder open in Atom. Thank you.
