### ISSUE TITLE
Can't start development server

### ISSUE THREAD

**Issue by myguidingstar** [expo/exp#55]
I tried `expo start` but I couldn't open it with my phone's expo client.
The output looks normal:
```
[exp] Your URL is

exp://{my-local-ip}:19000

[exp] Logs for your project will appear below. Press Ctrl+C to exit.
[exp] Dependency graph loaded.
```
Opening the url with browsers I got this:
```
{"error":"Error: ValidationError: child \"urlRandomness\" fails because [\"urlRandomness\" must be a string]"}
```
It's the blank project generated by `expo init` with no modifications. `expo doctor` show no errors
Diagnostics url https://exp-xde-diagnostics.s3.amazonaws.com/myguidingexpo-eed09bc8-2ab8-49db-a9f1-0cf7ae8e2e5a.tar.gz

**Comment by myguidingstar** [comment]
It works with "--offline" argument

**Comment by ShaneXie** [comment]
run into same problem, solved the problem by changing `"urlRandomness": null` to `"urlRandomness": "2v-w3z"` in `.expo/settings.json
dont know why tho.
