### ISSUE TITLE
npm Error: Not Found: @ccheever/inquirer@^0.9.5

### ISSUE THREAD

**Issue by Nicksapp** [expo/exp#58]
At the first step: `npm install -g exp` .
When I'm trying to install exp like that, npm throw `npm ERR! 404 Not Found: @ccheever/inquirer@0.9.5`,how to solve it?(My npm is in latest version)

**Comment by ccheever** [comment]
What version of `npm` are you using? It sounds like 5? Maybe try npm4
instead of npm5.
That package does live on npm and I was able to just successfully install
it.
Or maybe just try again? Maybe npm's servers had a hiccup.

**Comment by dikaiosune** [comment]
Hi! As requested in the issue template please open issues against https://github.com/expo/expo. As @ccheever mentioned it sounds like this was either an issue with npm 5 or with a temporary network problem on npm's end. If you're still having issues with this please open a new issue at expo/expo. Thanks!

**Comment by EzioKissshot** [comment]
@Nicksapp Hi, I have the same problem in China too. After that I use another npm source, then it works.

I use
`npm install -g exp --registry=https://registry.npm.taobao.org`

Maybe you can try it.
