### ISSUE TITLE
Add option to detach only iOS or Android

### ISSUE THREAD

**Issue by leo108** [expo/exp#60]
In some cases, we may only need to detach one platform's code, e.g.  https://github.com/expo/expo/issues/317

**Comment by dikaiosune** [comment]
Hi! This seems like a great idea. Can you please open a feature request on https://expo.canny.io? Also note for future reference that github issues should be filed against https://github.com/expo/expo, as requested in the issue template. Thanks!

**Comment by flieks** [comment]
i also have this problem now. I only needed an android native module. And now having problems getting IOS working (struggling with cocoapods errors in xcode)
