### ISSUE TITLE
Exp build:ios fails to validate credentials

### ISSUE THREAD

**Issue by Swolebrain** [expo/exp#62]
Trying to build an app that was working fine before, getting the following error:

`Unable to validate credentials. Request ID 28ef4340-7489-11e7-8971-9bc938555952, message: Internal error occurred. Please try again in a few minutes or contact support.
`

Went on the developer site and revoked all the certificates i had, still nothing. What can I do?

**Comment by Swolebrain** [comment]
I just had to wait a while apparently, servers busy or something.

**Comment by dikaiosune** [comment]
Hi! Sorry we missed this. As the issue template suggests, we only monitor expo/expo regularly. Sounds like you got this sorted out, please open an issue on https://github.com/expo/expo if you hit issues again!
