### ISSUE TITLE
Unable to fetch distribution certificate.  Unable to add new certificate to your account (maximum number reached).

### ISSUE THREAD

**Issue by jpca999** [expo/exp#65]
![image](https://user-images.githubusercontent.com/1026325/29846162-aad527ea-8ce3-11e7-9f3b-5e364498ab1e.png)
Here's the command that I used to create the ios build 

$   exp build:ios -c

Q: Does expo provides some UI where I can do and edit the certificates ?

**Comment by dikaiosune** [comment]
Hi! Please refer to the issue template, we don't normally monitor this repository. The Apple developer portal provides UI for revoking your certificates.
