### ISSUE TITLE
Error starting tunnel: Error: Error: failed to start tunnel while building

### ISSUE THREAD

**Issue by mstmustisnt** [expo/exp#66]
Hi, 
Getting this error while building android app:
```
Error starting tunnel: Error: Error: failed to start tunnel
```

But the build process is successful, apk is created but corrupt.

*Is this error critical?*

 Build ID: e86994ae-fce2-4f36-bd2c-9cffdec97d79

**Comment by nikki93** [comment]
We are maintaining all issues at https://github.com/expo/expo (common for all our tools) so please post there, as indicated in the issue template. Thank you. :)
