### ISSUE TITLE
[exp] Android: There was an error with this build.

### ISSUE THREAD

**Issue by varakal** [expo/exp#67]
Hey, this is my first time building an android application through exp. The app runs fine on expo but there is no stacktrace for the build fail. Could you assist me with the issue.

[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Starting build process...
[exp] Publishing...
[exp] Building iOS bundle
[exp] Building Android bundle
[exp] Analyzing assets
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] Published
[exp] Your URL is

https://exp.host/@varakal/your-app-slug

[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] Build ID: 214eb66d-3450-43e4-916f-7a4452c473bd
[exp] Run `exp build:status` to monitor it.

E:\bills>exp build:status
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] Android: There was an error with this build.

app.json:

{
"expo": {
   name: "billsplit",
   icon: "E:\bills\rupee-512.png",
   version: "1.0.0",
   slug: "your-app-slug",
    "sdkVersion": "20.0.0",
   ios: {
     bundleIdentifier: "com.billsplit.billsplit",
   },
   android: {
     package: "com.billsplit.billsplit",
   }
  }
     
}

**Comment by ide** [comment]
Hi, it looks like our builder had trouble parsing your icon, our logs say `Error: Invalid URI "e:/ills%0Dupee-512.png"`. Could you please (a) verify that your app.json is encoded with UTF-8, and (b) also try using a relative path for your icon? You also should be able to use forward slashes in the path.

**Comment by varakal** [comment]
@ide : Thanks for the update. Was able to successfully build the project.
