### ISSUE TITLE
[exp] connect ETIMEDOUT 35.184.55.1:443

### ISSUE THREAD

**Issue by milad1367** [expo/exp#68]
i have problems with build production apk for android and ios . 

```

C:\Users\admin\Desktop\gitlab\sirin>exp build:android
[exp] Making sure project is set up correctly...
/[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] connect ETIMEDOUT 35.184.55.1:443
[exp] Set EXPO_DEBUG=true in your env to view the stack trace.

C:\Users\admin\Desktop\gitlab\sirin>
```

**Comment by dikaiosune** [comment]
Hi! Please open issues against https://github.com/expo/expo, per the issue template.

It looks like this is a problem with your internet connection -- make sure you can reach other websites?

Giving this a close, please reopen on expo/expo if you're still having problems.
