### ISSUE TITLE
exp init unexpected EOF

### ISSUE THREAD

**Issue by divyaksh-shukla** [expo/exp#69]
*$ sudo exp init*
? Choose a project name: first-project
? Choose a template type: blank
[exp] Downloading project files...
[exp] Extracting project files...

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Process exited with non-zero code: 2

*$ exp --version*
44.0.0

*$ yarn --version*
1.0.2

*$ watchman -v*
4.1.0

I don't understand where did I go wrong in the installation. I also got this warning on installation:
 **+-- UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0**
**npm WARN react-redux@5.0.6 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none was installed.**

I tried all possible methods of resolving this warning

Linux version
*$ uname -a*
Linux Ideapad-Z570 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dikaiosune** [comment]
Hi! Please check the issue template before posting issues on this repository.

This error is usually due to a failed download -- please double check your network connection when creating new projects -- we have to download the template project before you can get started.
