### ISSUE TITLE
"Illegal option: -jarfile" Error when trying to generate SHA1 certificate for Google API key android

### ISSUE THREAD

**Issue by skasanibanyan** [expo/exp#71]
I am following the steps mentioned in the "building standalone apps" section of the Google authentication integration and I am stuck at the step to generate "SHA-1 certificate fingerprint" as per the link _[https://docs.expo.io/versions/latest/sdk/google.html#run-keytool--list--printcert--jarfile-growlerapk--grep-sha1--awk--print-2--where-growlerapk-is-the-name-of-the-apk-produced-in-step-1](https://docs.expo.io/versions/latest/sdk/google.html#run-keytool--list--printcert--jarfile-growlerapk--grep-sha1--awk--print-2--where-growlerapk-is-the-name-of-the-apk-produced-in-step-1)_

I get an error "**Illegal option:  -jarfile**" when i run the command "**keytool -list -printcert -jarfile growler.apk | grep SHA1 | awk '{ print $2 }**'"

I see the same command is used in building standalone android app for facebook authentication as well.  Please help me with this issue.

**Comment by quinlanj** [comment]
You most likely have to update your `keytool` binary. See
https://forums.expo.io/t/generate-androidstandaloneappclientid-help/3422/7
