### ISSUE TITLE
Build iOS failure

### ISSUE THREAD

**Issue by fabiocastrodev** [expo/exp#74]
We need your Apple ID/password to manage certificates and provisioning profiles
from your Apple Developer account.
? What's your Apple ID? xxxxxxxx
? Password? ********
? What is your Apple Team ID (you can find that on this page: https://developer
.apple.com/account/#/membership)? Personal Team
[exp] Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and t
ry again.
[exp] Unable to validate credentials. Request ID 19785750-b406-11e7-9fca-971d4d9
2d8d8, message: Internal error occurred. Please try again in a few minutes or co
ntact support.

Has anyone had this problem?

**Comment by dikaiosune** [comment]
Hi! Per the issue template please post to our forums or the issue tracker at https://github.com/expo/expo

We're seeing this error from fastlane: `No teams available on the Developer Portal You must accept an invitation to a team for it to be available To learn more about teams and how to use them visit https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html Your account is in no teams`
