### ISSUE TITLE
API Response Error: Not authorized

### ISSUE THREAD

**Issue by clementino36** [expo/exp#77]
I started getting this error message today as i tried to `exp build:ios` & `exp build:android` . I don't recall doing anything in particular except upgrading `exp` to 45.0.2. 
I tried downgrading it and building again, same error.
I couldn't find the cause of this error anywhere. Any idea ?

Sorry for posting this issue here but I figured this was specifically an `exp` error...
![capture](https://user-images.githubusercontent.com/6041593/32051565-66f38f72-ba55-11e7-9a1b-3443084cd379.PNG)

**Comment by clementino36** [comment]
I guess this has something to do with https://forums.expo.io/t/2017-10-25-issues-with-logging-into-expo-developer-accounts/4236/9 .

I'll wait and see.

**Comment by ide** [comment]
Hi - can you try logging out (`exp logout`) and logging back in (`exp login`)?

**Comment by clementino36** [comment]
I was able to login and build again, thank you :)
