### ISSUE TITLE
API Response Error: Not authorized

### ISSUE THREAD

**Issue by cseelus** [expo/exp#80]
Since about yesterday, I can't make any new builds, it fails with: 

![screen shot 2017-11-01 at 17 39 40](https://user-images.githubusercontent.com/3188392/32285786-ae52856e-bf2b-11e7-97eb-bc0696001e86.png)

`exp` does not even ask for my credentials, although the `-c` flag is used. 

Versions tested are 45.0.2, then 45.1.0, no two factor auth is used. 

Any other thing I could do to force `exp` to ask for my credentials?

**Comment by skevy** [comment]
Hi @cseelus, please try re-logging in with `exp login` and see if that fixes your problem.

**Comment by cseelus** [comment]
Thanks @skevy, that did the trick. May be helpful to add that hint to the error from above.
