### ISSUE TITLE
exp build:ios -c -> Unable to validate credentials. Message: Two-factor authentication isn't supported (yet -- stay tuned!)

### ISSUE THREAD

**Issue by Inlesco** [expo/exp#81]
When trying to run `exp build:ios -c` and after entering the Apple id, password and Apple Team ID, I get this:

```
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID f59533e0-bfa3-11e7-96dc-a793728006b9, message: Two-factor authentication isn't supported (yet -- stay tuned!).
```
And so far, I haven't been able to find any hints on how exactly to solve this... Could you include some hints right in the console for each possible error code?

**Comment by ide** [comment]
The issue is that you have two-factor authentication (ex: SMS code) enabled on your account and we don't support that right now.

**Comment by Inlesco** [comment]
@ide Are there any plans to support it?

**Comment by ide** [comment]
Yes, it's in the works but I don't have a time estimate. Hopefully before New Year's?

**Comment by Inlesco** [comment]
@ide ok, thanks for the estimate. 

In the meantime, are there any alternative solutions for this without having to disable 2-factor auth on one's Apple ID? 

Is there any other way to build a standalone app and creating an Xcode project with Expo? Do I really need to `eject` as it's the only way at the moment?

**Comment by JonathanPorta** [comment]
@ide Do you know if app-specific passwords are supported?

**Comment by ide** [comment]
No they are not -- only 2FA-less accounts are supported right now.

**Comment by dikaiosune** [comment]
Hi everyone! As I commented on this other thread, this should now be supported if you pass the `--local-auth` flag to `exp build:ios`. See https://github.com/expo/expo/issues/160#issuecomment-348375652 for details, and please report any issues with the new flow over on expo/expo. We'll make it the default once we're sure it's working for everyone!
