### ISSUE TITLE
exp cli never finds my keystore to upload

### ISSUE THREAD

**Issue by softnodelabs** [expo/exp#87]
Hi!

I'm trying a standalone android build but when I select option 2 in the command line and fill in the path to my keystore, I keep getting the message "File does not exist". I tried both relative and absolute path.

My system: Windows 10
node v8.8.1
npm v5.4.2

I appreciate any help.

**Comment by dikaiosune** [comment]
Hi, can you try with the latest version of exp? There was a small bug introduced by some cleanup code, but I believe the fix has been released now.

If updating exp doesn't fix it for you, please open an issue on https://github.com/expo/expo per the issue template.
