### ISSUE TITLE
Impossible to login Expo xde

### ISSUE THREAD

**Issue by Tadotte** [expo/exp#90]
Hello all,
I downloaded and installed Expo xde but when I try to connect with github and with my login, he puts me this: EACCES: permission denied, open '/Users/Baloo/.expo/state.json'
I have already uninstalled and reinstalled several times and even deleted the .json but nothing makes it I always have the same error.
I am running on OS X 10.9.5.

**Comment by dikaiosune** [comment]
Hi! As the issue template requests, please file issues against https://github.com/expo/expo.

I'd recommend making sure that your user has write permission to your home directory, perhaps by running something like `sudo chown -R Baloo:Baloo ~/.expo` (WARNING: this might not work, it might cause problems on your machine, and you should understand what chown does before running it as root).

**Comment by Tadotte** [comment]
It's work !
it was sudo chmod -R 777 .expo/

Thank you very much for your help :D

2017-12-06 20:39 GMT+01:00 Adam Perry <notifications@github.com>:
