### ISSUE TITLE
Corrupt APK after build

### ISSUE THREAD

**Issue by asela-wijesinghe** [expo/exp#91]
I tried building android apk from `exp build:android` all expo projects are built fine and running on the android device except for a one type of app (after checking for 5-6 hours) doesn't seem to work as expected. when i use `exp init ` and create a **project with tabs** and after i build it APK seems to throw error 

> there was a problem while parsing the package

but in all other occasions i created testing apps and they working fine in the device.only this type.
can someone please check whether i am right and find a fix? 

This is my full story from morning in the forum.
Link:  [https://forums.expo.io/t/corrupt-apk-after-build/5487](url)

**Comment by dikaiosune** [comment]
Hi! Per the issue template, can you please open this issue on https://github.com/expo/expo? It would also help us a lot if you could provide a reproduction we can use to diagnose what's happening here. Maybe a link to the project repository and the APK you built from it?

**Comment by asela-wijesinghe** [comment]
@dikaiosune yes i will refer you to the same error i did put in the expo and i will refer the resources. Thanks mate :)  expo #1094
