### ISSUE TITLE
error in creating first project

### ISSUE THREAD

**Issue by Mifayo** [expo/exp#92]
> ? Choose a template type: blank
[exp] Downloading project files...
[exp] Extracting project files...
Process exited with non-zero code: 2
ERROR: Unexpected end of data : blank-23.0.0.tar
> Process exited with non-zero code: 2

any help here ?

**Comment by fson** [comment]
Hey! The previous version of exp had a bug where, if the download was interrupted, it stored the incomplete template package in cache. I think this is the error you are seeing.

Can you ensure you have the latest version of exp installed, clear the cache,
```
rm ~/.expo/starter-app-cache/*.tar.gz
```
and then try again?

**Comment by Mifayo** [comment]
it works thanks a lot <3
