### ISSUE TITLE
[exp] Can't determine exponent directory

### ISSUE THREAD

**Issue by trustfall** [expo/exp#94]
```
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
Validating project manifest...
Skipping iOS because you are not running macOS.
Moving Android project files...
Downloading Android code...
[exp] Can't determine exponent directory
[exp] Set EXPO_DEBUG=true in your env to view the stack trace.
```

this is happening on multiple machines, just trying to run `exp init` followed by `exp detach`

**Comment by mauroporrasp** [comment]
I made it work issuing:
`EXPO_UNIVERSE_DIR=.expo EXPO_DEBUG=true exp detach`

**Comment by digitaledge** [comment]
Same issue was reported here: https://github.com/expo/expo/issues/1113

**Comment by terribleben** [comment]
Thanks for the report, we're tracking the fix [here](https://github.com/expo/expo/issues/1133).
