### ISSUE TITLE
Android: There was an error with this build.

### ISSUE THREAD

**Issue by ToothpickFactory** [expo/exp#95]
Error building Android.
Build ID: **62b9e145-357f-47d2-97c6-1c48a7948df6**

[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Starting build process...
[exp] Publishing...
[exp] Building iOS bundle
[exp] Building Android bundle
[exp] Analyzing assets
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] Published
[exp] Your URL is
[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] Build ID: 62b9e145-357f-47d2-97c6-1c48a7948df6
[exp] Run `exp build:status` to monitor it.

**Comment by ide** [comment]
The build logs say:
```
AAPT err(Facade for 1645194979) : No Delegate set : lost message:libpng error: Not a PNG file
```

It seems like there's some asset in your project that's not a PNG file that's expected to be one.  That's the extent of the error, it doesn't say what file it is but hopefully is a pointer in the right direction.
